unique_ids:
  forms:
    HomePage: T5NX5ONWFEOB5RKCUES3KX33JMPZIC7G
  modules: {}
  server_modules:
    Dictionary: '1716990931667103082206714.3946'
  assets:
    standard-page.html: 5VTRZCKC5TY2TSL6PBVKFJLRVF63EP6Q
    theme.css: HSS4JBGWIOQJDGZQHCXJUH5MUDDNQVE3
  scripts: {}
