unique_ids:
  forms:
    HomePage: GBWAD7YKVUFZ3IV6G6OM6CVJ3BQDU2CM
  modules: {}
  server_modules:
    Dictionary: X5RTLOYMHXKDIGZOPLFQQ4YLNAU6UHCF
    OpenAI: L7KE7SFPBIAUENNN6KR7RX7S4UP3WPTZ
    StaticAI: VCNC5ZC2A5QOIL5N7VHCD3Y33M44LEVU
  assets:
    standard-page.html: LO5GPKK6ISDBANIXX7PIGHXQF5QEY7RA
    theme.css: NFNLPSRQQSLK5P7AUNPICQV6Z7M42HIO
  scripts: {}
