unique_ids:
  forms:
    HomePage: GBWAD7YKVUFZ3IV6G6OM6CVJ3BQDU2CM
    HomePage.PracticeForm: '1717681548028780237483138.5244'
    HomePage.WordListForm: '1717681520526133063615955.05244'
    HomePage.WordListForm.RowTemplate1: '171768483382612023794360.094707'
  modules: {}
  server_modules:
    Handlers: 5AC2H3SKM6V3TWM5CO3LE7FYP4UCYAHV
    OpenAI: L7KE7SFPBIAUENNN6KR7RX7S4UP3WPTZ
    StaticAI: VCNC5ZC2A5QOIL5N7VHCD3Y33M44LEVU
    WordList: AYKDIMZAMUYETWSQDYKWYFWZXMJF5HBI
  assets:
    standard-page.html: LO5GPKK6ISDBANIXX7PIGHXQF5QEY7RA
    theme.css: NFNLPSRQQSLK5P7AUNPICQV6Z7M42HIO
  scripts: {}
