unique_ids:
  forms:
    HomePage: GBWAD7YKVUFZ3IV6G6OM6CVJ3BQDU2CM
    HomePage.PracticeForm: '1717681548028780237483138.5244'
    HomePage.WordListForm: '1717681520526133063615955.05244'
    HomePage.WordListForm.WordRowTemplate: QAW27NISICUT2AU7YMFPP4TLCWZVDMZC
  modules:
    HomePage.HomePage: WDIBEEJSD7FI62J5ZBLOHO3QYJNJK7HU
    HomePage.PracticeForm.PracticeForm: 7NZGQ5H7TJ35ORPA5DFNACF7NFM3H3SN
    HomePage.WordListForm.WordListForm: KV6PBGPFNUQBYR7LTWJDUYOR3B7VPE3I
    HomePage.WordListForm.WordRowTemplate.WordRowTemplate: CEMDG4XJ2OME3MYPXB4LKZ5LL7X2GZBG
  server_modules:
    Handlers: 5AC2H3SKM6V3TWM5CO3LE7FYP4UCYAHV
    OpenAI: L7KE7SFPBIAUENNN6KR7RX7S4UP3WPTZ
    StaticAI: VCNC5ZC2A5QOIL5N7VHCD3Y33M44LEVU
    Users: PZRD5S43VKLC45SKF5NH32FM63TM77HP
    WordList: AYKDIMZAMUYETWSQDYKWYFWZXMJF5HBI
  assets:
    standard-page.html: LO5GPKK6ISDBANIXX7PIGHXQF5QEY7RA
    theme.css: NFNLPSRQQSLK5P7AUNPICQV6Z7M42HIO
  scripts: {}
