unique_ids:
  forms:
    HomePage: GBWAD7YKVUFZ3IV6G6OM6CVJ3BQDU2CM
    WordListForm: '1717673429133298946525981.8764'
  modules: {}
  server_modules:
    Handlers: 5AC2H3SKM6V3TWM5CO3LE7FYP4UCYAHV
    OpenAI: L7KE7SFPBIAUENNN6KR7RX7S4UP3WPTZ
    StaticAI: VCNC5ZC2A5QOIL5N7VHCD3Y33M44LEVU
    WordList: AYKDIMZAMUYETWSQDYKWYFWZXMJF5HBI
  assets:
    standard-page.html: LO5GPKK6ISDBANIXX7PIGHXQF5QEY7RA
    theme.css: NFNLPSRQQSLK5P7AUNPICQV6Z7M42HIO
  scripts: {}
